### ISSUE TITLE
Converting to onnx

### ISSUE THREAD

**Issue by MetaDev** [anibali/dsntnn#10] opened 2019-02-17 09:39 UTC
I would like to convert the model to ONNX format but, the operators flip and linspace are not supported. Is there a workaround for this?
Thanks

**Comment by anibali** [comment] 2019-02-18 02:42
If you are using DSNT at the output, one option is to save the model up until (but excluding) the DSNT-related operations. Since those layers don't have weights anyway, saving them is not important. Kind of like how you don't need to save the loss function.

**Comment by anibali** [comment] 2019-05-02 04:13
This is effectively a duplicate of https://github.com/anibali/dsntnn/issues/9

**Closed by anibali** 2019-05-02 04:13 UTC
Labels: duplicate
